name: Build and Upload
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: "18"
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Fetch environment variables
        id: fetch-env
        run: |
          RESPONSE=$(curl -s -f -w "%{http_code}" -X GET "{{BACKEND_URL}}/api/environment/variables/{{REPO_ID}}" -H "Authorization: Bearer ${{secrets.ENV_ACCESS_TOKEN}}" -o envs.json)

          if [ "$RESPONSE" != "200" ]; then
            echo "::error::Failed to fetch environment variables. Status code: $RESPONSE"
            exit 1
          fi

          if [ -s envs.json ] && [ "$(cat envs.json)" != "{}" ]; then
            echo "Creating .env file from fetched variables."
            jq -r 'to_entries|map("\(.key)=\"\(.value|tostring)\"")|.[]' envs.json > .env
            echo "Generated .env file:"
            cat .env
          else
            echo "No environment variables found. Skipping .env creation."
          fi

      - name: Install dependencies
        id: install
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Installing dependencies with npm ci..."
            npm ci
          else
            echo "Installing dependencies with npm install..."
            npm install
          fi

      - name: Build project
        id: build
        run: |
          echo "Running build command: {{BUILD_COMMAND}}"
          {{BUILD_COMMAND}}

      - name: Verify build output
        id: verify
        run: |
          if [ ! -d "./{{BUILD_DIR}}" ]; then
            echo "::error::Build directory not found: {{BUILD_DIR}}"
            exit 1
          fi
          echo "Build directory verified: {{BUILD_DIR}}"

      - name: Zip build output
        id: zip
        run: |
          zip -r dist.zip ./{{BUILD_DIR}}
          echo "Build output zipped successfully"

      - name: Upload to backend
        id: upload
        run: |
          echo "Uploading build to backend..."
          RESPONSE=$(curl -s -f -w "%{http_code}" -X POST \
            "{{BACKEND_URL}}/api/upload/{{REPO_ID}}" \
            -F "file=@dist.zip" \
            -F "projectSlug={{PROJECT_SLUG}}" \
            -F "ownerLogin={{OWNER_LOGIN}}" \
            -F "repoName={{REPO_NAME}}" \
            -F "userEmail={{USER_EMAIL}}" \
            -F "githubId={{GITHUB_ID}}" \
            -F "repoId={{REPO_ID}}" \
            -H "Authorization: Bearer ${{secrets.ENV_ACCESS_TOKEN}}" \
            -H "Accept: application/json" \
            -o response.txt)

          if [ "$RESPONSE" != "200" ]; then
            echo "::error::Failed to upload build. Status code: $RESPONSE"
            cat response.txt
            exit 1
          fi
          echo "Build uploaded successfully"
