name: Build and Upload
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Fetch environment variables
        run: |
          curl -s -f -X GET "{{BACKEND_URL}}/api/envs/{{GITHUB_ID}}/{{REPO_NAME}}" -H "Authorization: Bearer ${{ secrets.ENV_ACCESS_TOKEN }}" -o envs.json

          if [ -s envs.json ] && [ "$(cat envs.json)" != "{}" ]; then
            echo "Creating .env file from fetched variables."
            jq -r 'to_entries|map("\(.key)=\"\(.value|tostring)\"")|.[]' envs.json > .env
            echo "Generated .env file:"
            cat .env
          else
            echo "No environment variables fetched or file is empty. Skipping .env creation."
          fi

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: {{BUILD_COMMAND}}
      - name: Zip dist folder
        run: zip -r dist.zip ./{{BUILD_DIR}}

      - name: Upload to backend
        run: |
          curl -X POST {{BACKEND_URL}}/api/upload \
            -F "file=@dist.zip" \
            -F "projectSlug={{PROJECT_SLUG}}" \
            -F "ownerLogin={{OWNER_LOGIN}}" \
            -F "repoName={{REPO_NAME}}" \
            -F "userEmail={{USER_EMAIL}}" \
            -F "githubId={{GITHUB_ID}}"
